services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - node

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    command: sh -c "npm install && npm run build"

networks:
  laravel:
    driver: bridge
